version: '3'
services:
  symfony-nginx:
    build:
      context: ./docker/development
      dockerfile: nginx.docker
    volumes:
      - C:\Projects\symfony_eliseev:/app
    depends_on:
      - symfony-php-fpm
    ports:
      - "8080:80"
  symfony-php-fpm:
    build:
      context: ./docker/development
      dockerfile: php-fpm.docker
    volumes:
      - C:\Projects\symfony_eliseev:/app
  symfony-php-cli:
    build:
      context: ./docker/development
      dockerfile: php-cli.docker
    volumes:
      - C:\Projects\symfony_eliseev:/app
